### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RogerE**
Fix for using default styles

### CODE REVIEW

**Comment by delef** [comment]
Hi! Thanks for your PR.

if you need use default styles, then you don’t need use `renderer`. The instruction in README need only for setting `will_paginate-bootstrap4`.

**Comment by RogerE** [comment]
Hi,
we have a site with a public area that uses bootstrap and a private admin area that do not. So for the admin area we want to disable the bootstrap styling, but the instructions provided in the readme on how to do this  does not work for us. The suggested change does the job for our set up.


RogEr

**Comment by delef** [comment]
Yes, I agree with you, but this refers to the main project (https://github.com/mislav/will_paginate), but we but we work to support Bootstrap 4 and nothing more.

https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/view_helpers/link_renderer.rb

Thanks again for your interest in our project! 🙂

**Comment by RogerE** [comment]
Hi,
the suggested change is for the README for this project(delef/will_paginate-bootstrap4). 

The README says the you can get default styling with:

`<%= will_paginate @collection, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>`

But this uses the rendering from this project which will add bootstrap styling. To get default styling you must us the renderer from the main project:

`<%= will_paginate @collection, renderer: WillPaginate::ActionView::LinkRenderer %>`

**Comment by delef** [comment]
I understand you now. Thanks 🙂

**Pull request merged**
